local LSM = LibStub('LibSharedMedia-3.0')

print("test")
-- Fonts
LSM:Register('font','Expressway', [[Interface\AddOns\ProjectHopes_Media\Media\Fonts\Expressway.ttf]])
LSM:Register('font','Noto', [[Interface\AddOns\ProjectHopes_Media\Media\Fonts\NotoSans.ttf.ttf]])

-- Statusbar Textures
LSM:Register('statusbar','HopesUI', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\HopesUI.tga]])
LSM:Register('statusbar','Health Fill', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\Grid2_HP_Fill.tga]])
LSM:Register('statusbar','Health Background', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\Grid2_HP_Background.tga]])
LSM:Register('statusbar','Blizzard Cast', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\blizzcast.tga]])
LSM:Register('statusbar','Blizzard Cast Background', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\blizzcastback.tga]])
LSM:Register('statusbar','Blizzard Cast Channel', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\blizzcastchannel.tga]])
LSM:Register('statusbar','Blizzard Cast Nonbreakable', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\blizzcastnonbreakable.tga]])
LSM:Register('statusbar','Blizzard Desat', [[Interface\AddOns\ProjectHopes_Media\Media\Statusbar\blizzdesat.tga]])

-- Borders
LSM:Register('border', 'HopesUI', [[Interface\Addons\ProjectHopes_Media\Media\Borders\HopesUI.tga]])
LSM:Register('border', 'HopesUI Light', [[Interface\Addons\ProjectHopes_Media\Media\Borders\HopesUI_Light.tga]])

-- Sounds
LSM:Register("sound","|cffffc907Add|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Add.ogg]])
LSM:Register("sound","|cffffc907Adds|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Adds.ogg]])
LSM:Register("sound","|cffffc907AoE|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\AoE.ogg]])
LSM:Register("sound","|cffffc907Avoid|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Avoid.ogg]])
LSM:Register("sound","|cffffc907Bait|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Bait.ogg]])
LSM:Register("sound","|cffffc907Behind|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Behind.ogg]])
LSM:Register("sound","|cffffc907Bloodlust|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Bloodlust.ogg]])
LSM:Register("sound","|cffffc907CC|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\CC.ogg]])
LSM:Register("sound","|cffffc907Charge|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Charge.ogg]])
LSM:Register("sound","|cffffc907Clear|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Clear.ogg]])
LSM:Register("sound","|cffffc907Dance|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Dance.ogg]])
LSM:Register("sound","|cffffc907Dispel|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Dispel.ogg]])
LSM:Register("sound","|cffffc907Defensive|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Defensive.ogg]])
LSM:Register("sound","|cffffc907Dodge|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Dodge.ogg]])
LSM:Register("sound","|cffffc907Fixate|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Fixate.ogg]])
LSM:Register("sound","|cffffc907Frontal|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Frontal.ogg]])
LSM:Register("sound","|cffffc907Hide|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Hide.ogg]])
LSM:Register("sound","|cffffc907Inside|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Inside.ogg]])
LSM:Register("sound","|cffffc907Interrupt|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Interrupt.ogg]])
LSM:Register("sound","|cffffc907Kite|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Kite.ogg]])
LSM:Register("sound","|cffffc907Knock|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Knock.ogg]])
LSM:Register("sound","|cffffc907Link|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Link.ogg]])
LSM:Register("sound","|cffffc907LOS|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\LOS.ogg]])
LSM:Register("sound","|cffffc907Move|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Move.ogg]])
LSM:Register("sound","|cffffc907MoveOut|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\MoveOut.ogg]])
LSM:Register("sound","|cffffc907Orbs|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Orbs.ogg]])
LSM:Register("sound","|cffffc907Out|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Out.ogg]])
LSM:Register("sound","|cffffc907OutofRange|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\OutofRange.ogg]])
LSM:Register("sound","|cffffc907Pull|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Pull.ogg]])
LSM:Register("sound","|cffffc907Run|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Run.ogg]])
LSM:Register("sound","|cffffc907Soak|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Soak.ogg]])
LSM:Register("sound","|cffffc907Spike|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Spike.ogg]])
LSM:Register("sound","|cffffc907Spikes|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Spikes.ogg]])
LSM:Register("sound","|cffffc907Spread|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Spread.ogg]])
LSM:Register("sound","|cffffc907Totem|r", [[Interface\Addons\ProjectHopes_Media\Media\Sounds\Totem.ogg]])
